[profile.default]
libs = ["lib"]

# Compiler Options
bytecode_hash = "none"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
solc_version = "0.8.26"
via_ir = false

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[fmt]
line_length = 100
multiline_func_header = "params_first"

[rpc_endpoints]
base = "https://base.merkle.io"
